GLGUNAKANFUNGSI(void,PFNGLPRIMITIVEBOUNDINGBOXARBPROC,glPrimitiveBoundingBoxARB,(GLfloat minX, GLfloat minY, GLfloat minZ, GLfloat minW, GLfloat maxX, GLfloat maxY, GLfloat maxZ, GLfloat maxW));
GLGUNAKANFUNGSI(GLuint64,PFNGLGETTEXTUREHANDLEARBPROC,glGetTextureHandleARB,(GLuint texture));
GLGUNAKANFUNGSI(GLuint64,PFNGLGETTEXTURESAMPLERHANDLEARBPROC,glGetTextureSamplerHandleARB,(GLuint texture, GLuint sampler));
GLGUNAKANFUNGSI(void,PFNGLMAKETEXTUREHANDLERESIDENTARBPROC,glMakeTextureHandleResidentARB,(GLuint64 handle));
GLGUNAKANFUNGSI(void,PFNGLMAKETEXTUREHANDLENONRESIDENTARBPROC,glMakeTextureHandleNonResidentARB,(GLuint64 handle));
GLGUNAKANFUNGSI(GLuint64,PFNGLGETIMAGEHANDLEARBPROC,glGetImageHandleARB,(GLuint texture, GLint level, GLboolean layered, GLint layer, GLenum format));
GLGUNAKANFUNGSI(void,PFNGLMAKEIMAGEHANDLERESIDENTARBPROC,glMakeImageHandleResidentARB,(GLuint64 handle, GLenum access));
GLGUNAKANFUNGSI(void,PFNGLMAKEIMAGEHANDLENONRESIDENTARBPROC,glMakeImageHandleNonResidentARB,(GLuint64 handle));
GLGUNAKANFUNGSI(void,PFNGLUNIFORMHANDLEUI64ARBPROC,glUniformHandleui64ARB,(GLint location, GLuint64 value));
GLGUNAKANFUNGSI(void,PFNGLUNIFORMHANDLEUI64VARBPROC,glUniformHandleui64vARB,(GLint location, GLsizei count, const GLuint64 *value));
GLGUNAKANFUNGSI(void,PFNGLPROGRAMUNIFORMHANDLEUI64ARBPROC,glProgramUniformHandleui64ARB,(GLuint program, GLint location, GLuint64 value));
GLGUNAKANFUNGSI(void,PFNGLPROGRAMUNIFORMHANDLEUI64VARBPROC,glProgramUniformHandleui64vARB,(GLuint program, GLint location, GLsizei count, const GLuint64 *values));
GLGUNAKANFUNGSI(GLboolean,PFNGLISTEXTUREHANDLERESIDENTARBPROC,glIsTextureHandleResidentARB,(GLuint64 handle));
GLGUNAKANFUNGSI(GLboolean,PFNGLISIMAGEHANDLERESIDENTARBPROC,glIsImageHandleResidentARB,(GLuint64 handle));
GLGUNAKANFUNGSI(void,PFNGLVERTEXATTRIBL1UI64ARBPROC,glVertexAttribL1ui64ARB,(GLuint index, GLuint64EXT x));
GLGUNAKANFUNGSI(void,PFNGLVERTEXATTRIBL1UI64VARBPROC,glVertexAttribL1ui64vARB,(GLuint index, const GLuint64EXT *v));
GLGUNAKANFUNGSI(void,PFNGLGETVERTEXATTRIBLUI64VARBPROC,glGetVertexAttribLui64vARB,(GLuint index, GLenum pname, GLuint64EXT *params));
GLGUNAKANFUNGSI(GLsync,PFNGLCREATESYNCFROMCLEVENTARBPROC,glCreateSyncFromCLeventARB,(struct _cl_context *context, struct _cl_event *event, GLbitfield flags));
GLGUNAKANFUNGSI(void,PFNGLCLAMPCOLORARBPROC,glClampColorARB,(GLenum target, GLenum clamp));
GLGUNAKANFUNGSI(void,PFNGLDISPATCHCOMPUTEGROUPSIZEARBPROC,glDispatchComputeGroupSizeARB,(GLuint num_groups_x, GLuint num_groups_y, GLuint num_groups_z, GLuint group_size_x, GLuint group_size_y, GLuint group_size_z));
GLGUNAKANFUNGSI(void,PFNGLDEBUGMESSAGECONTROLARBPROC,glDebugMessageControlARB,(GLenum source, GLenum type, GLenum severity, GLsizei count, const GLuint *ids, GLboolean enabled));
GLGUNAKANFUNGSI(void,PFNGLDEBUGMESSAGEINSERTARBPROC,glDebugMessageInsertARB,(GLenum source, GLenum type, GLuint id, GLenum severity, GLsizei length, const GLchar *buf));
GLGUNAKANFUNGSI(void,PFNGLDEBUGMESSAGECALLBACKARBPROC,glDebugMessageCallbackARB,(GLDEBUGPROCARB callback, const void *userParam));
GLGUNAKANFUNGSI(GLuint,PFNGLGETDEBUGMESSAGELOGARBPROC,glGetDebugMessageLogARB,(GLuint count, GLsizei bufSize, GLenum *sources, GLenum *types, GLuint *ids, GLenum *severities, GLsizei *lengths, GLchar *messageLog));
GLGUNAKANFUNGSI(void,PFNGLDRAWBUFFERSARBPROC,glDrawBuffersARB,(GLsizei n, const GLenum *bufs));
GLGUNAKANFUNGSI(void,PFNGLBLENDEQUATIONIARBPROC,glBlendEquationiARB,(GLuint buf, GLenum mode));
GLGUNAKANFUNGSI(void,PFNGLBLENDEQUATIONSEPARATEIARBPROC,glBlendEquationSeparateiARB,(GLuint buf, GLenum modeRGB, GLenum modeAlpha));
GLGUNAKANFUNGSI(void,PFNGLBLENDFUNCIARBPROC,glBlendFunciARB,(GLuint buf, GLenum src, GLenum dst));
GLGUNAKANFUNGSI(void,PFNGLBLENDFUNCSEPARATEIARBPROC,glBlendFuncSeparateiARB,(GLuint buf, GLenum srcRGB, GLenum dstRGB, GLenum srcAlpha, GLenum dstAlpha));
GLGUNAKANFUNGSI(void,PFNGLDRAWARRAYSINSTANCEDARBPROC,glDrawArraysInstancedARB,(GLenum mode, GLint first, GLsizei count, GLsizei primcount));
GLGUNAKANFUNGSI(void,PFNGLDRAWELEMENTSINSTANCEDARBPROC,glDrawElementsInstancedARB,(GLenum mode, GLsizei count, GLenum type, const void *indices, GLsizei primcount));
GLGUNAKANFUNGSI(void,PFNGLPROGRAMSTRINGARBPROC,glProgramStringARB,(GLenum target, GLenum format, GLsizei len, const void *string));
GLGUNAKANFUNGSI(void,PFNGLBINDPROGRAMARBPROC,glBindProgramARB,(GLenum target, GLuint program));
GLGUNAKANFUNGSI(void,PFNGLDELETEPROGRAMSARBPROC,glDeleteProgramsARB,(GLsizei n, const GLuint *programs));
GLGUNAKANFUNGSI(void,PFNGLGENPROGRAMSARBPROC,glGenProgramsARB,(GLsizei n, GLuint *programs));
GLGUNAKANFUNGSI(void,PFNGLPROGRAMENVPARAMETER4DARBPROC,glProgramEnvParameter4dARB,(GLenum target, GLuint index, GLdouble x, GLdouble y, GLdouble z, GLdouble w));
GLGUNAKANFUNGSI(void,PFNGLPROGRAMENVPARAMETER4DVARBPROC,glProgramEnvParameter4dvARB,(GLenum target, GLuint index, const GLdouble *params));
GLGUNAKANFUNGSI(void,PFNGLPROGRAMENVPARAMETER4FARBPROC,glProgramEnvParameter4fARB,(GLenum target, GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w));
GLGUNAKANFUNGSI(void,PFNGLPROGRAMENVPARAMETER4FVARBPROC,glProgramEnvParameter4fvARB,(GLenum target, GLuint index, const GLfloat *params));
GLGUNAKANFUNGSI(void,PFNGLPROGRAMLOCALPARAMETER4DARBPROC,glProgramLocalParameter4dARB,(GLenum target, GLuint index, GLdouble x, GLdouble y, GLdouble z, GLdouble w));
GLGUNAKANFUNGSI(void,PFNGLPROGRAMLOCALPARAMETER4DVARBPROC,glProgramLocalParameter4dvARB,(GLenum target, GLuint index, const GLdouble *params));
GLGUNAKANFUNGSI(void,PFNGLPROGRAMLOCALPARAMETER4FARBPROC,glProgramLocalParameter4fARB,(GLenum target, GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w));
GLGUNAKANFUNGSI(void,PFNGLPROGRAMLOCALPARAMETER4FVARBPROC,glProgramLocalParameter4fvARB,(GLenum target, GLuint index, const GLfloat *params));
GLGUNAKANFUNGSI(void,PFNGLGETPROGRAMENVPARAMETERDVARBPROC,glGetProgramEnvParameterdvARB,(GLenum target, GLuint index, GLdouble *params));
GLGUNAKANFUNGSI(void,PFNGLGETPROGRAMENVPARAMETERFVARBPROC,glGetProgramEnvParameterfvARB,(GLenum target, GLuint index, GLfloat *params));
GLGUNAKANFUNGSI(void,PFNGLGETPROGRAMLOCALPARAMETERDVARBPROC,glGetProgramLocalParameterdvARB,(GLenum target, GLuint index, GLdouble *params));
GLGUNAKANFUNGSI(void,PFNGLGETPROGRAMLOCALPARAMETERFVARBPROC,glGetProgramLocalParameterfvARB,(GLenum target, GLuint index, GLfloat *params));
GLGUNAKANFUNGSI(void,PFNGLGETPROGRAMIVARBPROC,glGetProgramivARB,(GLenum target, GLenum pname, GLint *params));
GLGUNAKANFUNGSI(void,PFNGLGETPROGRAMSTRINGARBPROC,glGetProgramStringARB,(GLenum target, GLenum pname, void *string));
GLGUNAKANFUNGSI(GLboolean,PFNGLISPROGRAMARBPROC,glIsProgramARB,(GLuint program));
GLGUNAKANFUNGSI(void,PFNGLPROGRAMPARAMETERIARBPROC,glProgramParameteriARB,(GLuint program, GLenum pname, GLint value));
GLGUNAKANFUNGSI(void,PFNGLFRAMEBUFFERTEXTUREARBPROC,glFramebufferTextureARB,(GLenum target, GLenum attachment, GLuint texture, GLint level));
GLGUNAKANFUNGSI(void,PFNGLFRAMEBUFFERTEXTURELAYERARBPROC,glFramebufferTextureLayerARB,(GLenum target, GLenum attachment, GLuint texture, GLint level, GLint layer));
GLGUNAKANFUNGSI(void,PFNGLFRAMEBUFFERTEXTUREFACEARBPROC,glFramebufferTextureFaceARB,(GLenum target, GLenum attachment, GLuint texture, GLint level, GLenum face));
GLGUNAKANFUNGSI(void,PFNGLSPECIALIZESHADERARBPROC,glSpecializeShaderARB,(GLuint shader, const GLchar *pEntryPoint, GLuint numSpecializationConstants, const GLuint *pConstantIndex, const GLuint *pConstantValue));
GLGUNAKANFUNGSI(void,PFNGLUNIFORM1I64ARBPROC,glUniform1i64ARB,(GLint location, GLint64 x));
GLGUNAKANFUNGSI(void,PFNGLUNIFORM2I64ARBPROC,glUniform2i64ARB,(GLint location, GLint64 x, GLint64 y));
GLGUNAKANFUNGSI(void,PFNGLUNIFORM3I64ARBPROC,glUniform3i64ARB,(GLint location, GLint64 x, GLint64 y, GLint64 z));
GLGUNAKANFUNGSI(void,PFNGLUNIFORM4I64ARBPROC,glUniform4i64ARB,(GLint location, GLint64 x, GLint64 y, GLint64 z, GLint64 w));
GLGUNAKANFUNGSI(void,PFNGLUNIFORM1I64VARBPROC,glUniform1i64vARB,(GLint location, GLsizei count, const GLint64 *value));
GLGUNAKANFUNGSI(void,PFNGLUNIFORM2I64VARBPROC,glUniform2i64vARB,(GLint location, GLsizei count, const GLint64 *value));
GLGUNAKANFUNGSI(void,PFNGLUNIFORM3I64VARBPROC,glUniform3i64vARB,(GLint location, GLsizei count, const GLint64 *value));
GLGUNAKANFUNGSI(void,PFNGLUNIFORM4I64VARBPROC,glUniform4i64vARB,(GLint location, GLsizei count, const GLint64 *value));
GLGUNAKANFUNGSI(void,PFNGLUNIFORM1UI64ARBPROC,glUniform1ui64ARB,(GLint location, GLuint64 x));
GLGUNAKANFUNGSI(void,PFNGLUNIFORM2UI64ARBPROC,glUniform2ui64ARB,(GLint location, GLuint64 x, GLuint64 y));
GLGUNAKANFUNGSI(void,PFNGLUNIFORM3UI64ARBPROC,glUniform3ui64ARB,(GLint location, GLuint64 x, GLuint64 y, GLuint64 z));
GLGUNAKANFUNGSI(void,PFNGLUNIFORM4UI64ARBPROC,glUniform4ui64ARB,(GLint location, GLuint64 x, GLuint64 y, GLuint64 z, GLuint64 w));
GLGUNAKANFUNGSI(void,PFNGLUNIFORM1UI64VARBPROC,glUniform1ui64vARB,(GLint location, GLsizei count, const GLuint64 *value));
GLGUNAKANFUNGSI(void,PFNGLUNIFORM2UI64VARBPROC,glUniform2ui64vARB,(GLint location, GLsizei count, const GLuint64 *value));
GLGUNAKANFUNGSI(void,PFNGLUNIFORM3UI64VARBPROC,glUniform3ui64vARB,(GLint location, GLsizei count, const GLuint64 *value));
GLGUNAKANFUNGSI(void,PFNGLUNIFORM4UI64VARBPROC,glUniform4ui64vARB,(GLint location, GLsizei count, const GLuint64 *value));
GLGUNAKANFUNGSI(void,PFNGLGETUNIFORMI64VARBPROC,glGetUniformi64vARB,(GLuint program, GLint location, GLint64 *params));
GLGUNAKANFUNGSI(void,PFNGLGETUNIFORMUI64VARBPROC,glGetUniformui64vARB,(GLuint program, GLint location, GLuint64 *params));
GLGUNAKANFUNGSI(void,PFNGLGETNUNIFORMI64VARBPROC,glGetnUniformi64vARB,(GLuint program, GLint location, GLsizei bufSize, GLint64 *params));
GLGUNAKANFUNGSI(void,PFNGLGETNUNIFORMUI64VARBPROC,glGetnUniformui64vARB,(GLuint program, GLint location, GLsizei bufSize, GLuint64 *params));
GLGUNAKANFUNGSI(void,PFNGLPROGRAMUNIFORM1I64ARBPROC,glProgramUniform1i64ARB,(GLuint program, GLint location, GLint64 x));
GLGUNAKANFUNGSI(void,PFNGLPROGRAMUNIFORM2I64ARBPROC,glProgramUniform2i64ARB,(GLuint program, GLint location, GLint64 x, GLint64 y));
GLGUNAKANFUNGSI(void,PFNGLPROGRAMUNIFORM3I64ARBPROC,glProgramUniform3i64ARB,(GLuint program, GLint location, GLint64 x, GLint64 y, GLint64 z));
GLGUNAKANFUNGSI(void,PFNGLPROGRAMUNIFORM4I64ARBPROC,glProgramUniform4i64ARB,(GLuint program, GLint location, GLint64 x, GLint64 y, GLint64 z, GLint64 w));
GLGUNAKANFUNGSI(void,PFNGLPROGRAMUNIFORM1I64VARBPROC,glProgramUniform1i64vARB,(GLuint program, GLint location, GLsizei count, const GLint64 *value));
GLGUNAKANFUNGSI(void,PFNGLPROGRAMUNIFORM2I64VARBPROC,glProgramUniform2i64vARB,(GLuint program, GLint location, GLsizei count, const GLint64 *value));
GLGUNAKANFUNGSI(void,PFNGLPROGRAMUNIFORM3I64VARBPROC,glProgramUniform3i64vARB,(GLuint program, GLint location, GLsizei count, const GLint64 *value));
GLGUNAKANFUNGSI(void,PFNGLPROGRAMUNIFORM4I64VARBPROC,glProgramUniform4i64vARB,(GLuint program, GLint location, GLsizei count, const GLint64 *value));
GLGUNAKANFUNGSI(void,PFNGLPROGRAMUNIFORM1UI64ARBPROC,glProgramUniform1ui64ARB,(GLuint program, GLint location, GLuint64 x));
GLGUNAKANFUNGSI(void,PFNGLPROGRAMUNIFORM2UI64ARBPROC,glProgramUniform2ui64ARB,(GLuint program, GLint location, GLuint64 x, GLuint64 y));
GLGUNAKANFUNGSI(void,PFNGLPROGRAMUNIFORM3UI64ARBPROC,glProgramUniform3ui64ARB,(GLuint program, GLint location, GLuint64 x, GLuint64 y, GLuint64 z));
GLGUNAKANFUNGSI(void,PFNGLPROGRAMUNIFORM4UI64ARBPROC,glProgramUniform4ui64ARB,(GLuint program, GLint location, GLuint64 x, GLuint64 y, GLuint64 z, GLuint64 w));
GLGUNAKANFUNGSI(void,PFNGLPROGRAMUNIFORM1UI64VARBPROC,glProgramUniform1ui64vARB,(GLuint program, GLint location, GLsizei count, const GLuint64 *value));
GLGUNAKANFUNGSI(void,PFNGLPROGRAMUNIFORM2UI64VARBPROC,glProgramUniform2ui64vARB,(GLuint program, GLint location, GLsizei count, const GLuint64 *value));
GLGUNAKANFUNGSI(void,PFNGLPROGRAMUNIFORM3UI64VARBPROC,glProgramUniform3ui64vARB,(GLuint program, GLint location, GLsizei count, const GLuint64 *value));
GLGUNAKANFUNGSI(void,PFNGLPROGRAMUNIFORM4UI64VARBPROC,glProgramUniform4ui64vARB,(GLuint program, GLint location, GLsizei count, const GLuint64 *value));
GLGUNAKANFUNGSI(void,PFNGLMULTIDRAWARRAYSINDIRECTCOUNTARBPROC,glMultiDrawArraysIndirectCountARB,(GLenum mode, const void *indirect, GLintptr drawcount, GLsizei maxdrawcount, GLsizei stride));
GLGUNAKANFUNGSI(void,PFNGLMULTIDRAWELEMENTSINDIRECTCOUNTARBPROC,glMultiDrawElementsIndirectCountARB,(GLenum mode, GLenum type, const void *indirect, GLintptr drawcount, GLsizei maxdrawcount, GLsizei stride));
GLGUNAKANFUNGSI(void,PFNGLVERTEXATTRIBDIVISORARBPROC,glVertexAttribDivisorARB,(GLuint index, GLuint divisor));
GLGUNAKANFUNGSI(void,PFNGLCURRENTPALETTEMATRIXARBPROC,glCurrentPaletteMatrixARB,(GLint index));
GLGUNAKANFUNGSI(void,PFNGLMATRIXINDEXUBVARBPROC,glMatrixIndexubvARB,(GLint size, const GLubyte *indices));
GLGUNAKANFUNGSI(void,PFNGLMATRIXINDEXUSVARBPROC,glMatrixIndexusvARB,(GLint size, const GLushort *indices));
GLGUNAKANFUNGSI(void,PFNGLMATRIXINDEXUIVARBPROC,glMatrixIndexuivARB,(GLint size, const GLuint *indices));
GLGUNAKANFUNGSI(void,PFNGLMATRIXINDEXPOINTERARBPROC,glMatrixIndexPointerARB,(GLint size, GLenum type, GLsizei stride, const void *pointer));
GLGUNAKANFUNGSI(void,PFNGLSAMPLECOVERAGEARBPROC,glSampleCoverageARB,(GLfloat value, GLboolean invert));
//GLGUNAKANFUNGSI(void,PFNGLACTIVETEXTUREARBPROC,glActiveTextureARB,(GLenum texture));
// GLGUNAKANFUNGSI(void,PFNGLCLIENTACTIVETEXTUREARBPROC,glClientActiveTextureARB,(GLenum texture));
// GLGUNAKANFUNGSI(void,PFNGLMULTITEXCOORD1DARBPROC,glMultiTexCoord1dARB,(GLenum target, GLdouble s));
// GLGUNAKANFUNGSI(void,PFNGLMULTITEXCOORD1DVARBPROC,glMultiTexCoord1dvARB,(GLenum target, const GLdouble *v));
// GLGUNAKANFUNGSI(void,PFNGLMULTITEXCOORD1FARBPROC,glMultiTexCoord1fARB,(GLenum target, GLfloat s));
// GLGUNAKANFUNGSI(void,PFNGLMULTITEXCOORD1FVARBPROC,glMultiTexCoord1fvARB,(GLenum target, const GLfloat *v));
// GLGUNAKANFUNGSI(void,PFNGLMULTITEXCOORD1IARBPROC,glMultiTexCoord1iARB,(GLenum target, GLint s));
// GLGUNAKANFUNGSI(void,PFNGLMULTITEXCOORD1IVARBPROC,glMultiTexCoord1ivARB,(GLenum target, const GLint *v));
// GLGUNAKANFUNGSI(void,PFNGLMULTITEXCOORD1SARBPROC,glMultiTexCoord1sARB,(GLenum target, GLshort s));
// GLGUNAKANFUNGSI(void,PFNGLMULTITEXCOORD1SVARBPROC,glMultiTexCoord1svARB,(GLenum target, const GLshort *v));
// GLGUNAKANFUNGSI(void,PFNGLMULTITEXCOORD2DARBPROC,glMultiTexCoord2dARB,(GLenum target, GLdouble s, GLdouble t));
// GLGUNAKANFUNGSI(void,PFNGLMULTITEXCOORD2DVARBPROC,glMultiTexCoord2dvARB,(GLenum target, const GLdouble *v));
// GLGUNAKANFUNGSI(void,PFNGLMULTITEXCOORD2FARBPROC,glMultiTexCoord2fARB,(GLenum target, GLfloat s, GLfloat t));
// GLGUNAKANFUNGSI(void,PFNGLMULTITEXCOORD2FVARBPROC,glMultiTexCoord2fvARB,(GLenum target, const GLfloat *v));
// GLGUNAKANFUNGSI(void,PFNGLMULTITEXCOORD2IARBPROC,glMultiTexCoord2iARB,(GLenum target, GLint s, GLint t));
// GLGUNAKANFUNGSI(void,PFNGLMULTITEXCOORD2IVARBPROC,glMultiTexCoord2ivARB,(GLenum target, const GLint *v));
// GLGUNAKANFUNGSI(void,PFNGLMULTITEXCOORD2SARBPROC,glMultiTexCoord2sARB,(GLenum target, GLshort s, GLshort t));
// GLGUNAKANFUNGSI(void,PFNGLMULTITEXCOORD2SVARBPROC,glMultiTexCoord2svARB,(GLenum target, const GLshort *v));
// GLGUNAKANFUNGSI(void,PFNGLMULTITEXCOORD3DARBPROC,glMultiTexCoord3dARB,(GLenum target, GLdouble s, GLdouble t, GLdouble r));
// GLGUNAKANFUNGSI(void,PFNGLMULTITEXCOORD3DVARBPROC,glMultiTexCoord3dvARB,(GLenum target, const GLdouble *v));
// GLGUNAKANFUNGSI(void,PFNGLMULTITEXCOORD3FARBPROC,glMultiTexCoord3fARB,(GLenum target, GLfloat s, GLfloat t, GLfloat r));
// GLGUNAKANFUNGSI(void,PFNGLMULTITEXCOORD3FVARBPROC,glMultiTexCoord3fvARB,(GLenum target, const GLfloat *v));
// GLGUNAKANFUNGSI(void,PFNGLMULTITEXCOORD3IARBPROC,glMultiTexCoord3iARB,(GLenum target, GLint s, GLint t, GLint r));
// GLGUNAKANFUNGSI(void,PFNGLMULTITEXCOORD3IVARBPROC,glMultiTexCoord3ivARB,(GLenum target, const GLint *v));
// GLGUNAKANFUNGSI(void,PFNGLMULTITEXCOORD3SARBPROC,glMultiTexCoord3sARB,(GLenum target, GLshort s, GLshort t, GLshort r));
// GLGUNAKANFUNGSI(void,PFNGLMULTITEXCOORD3SVARBPROC,glMultiTexCoord3svARB,(GLenum target, const GLshort *v));
// GLGUNAKANFUNGSI(void,PFNGLMULTITEXCOORD4DARBPROC,glMultiTexCoord4dARB,(GLenum target, GLdouble s, GLdouble t, GLdouble r, GLdouble q));
// GLGUNAKANFUNGSI(void,PFNGLMULTITEXCOORD4DVARBPROC,glMultiTexCoord4dvARB,(GLenum target, const GLdouble *v));
// GLGUNAKANFUNGSI(void,PFNGLMULTITEXCOORD4FARBPROC,glMultiTexCoord4fARB,(GLenum target, GLfloat s, GLfloat t, GLfloat r, GLfloat q));
// GLGUNAKANFUNGSI(void,PFNGLMULTITEXCOORD4FVARBPROC,glMultiTexCoord4fvARB,(GLenum target, const GLfloat *v));
// GLGUNAKANFUNGSI(void,PFNGLMULTITEXCOORD4IARBPROC,glMultiTexCoord4iARB,(GLenum target, GLint s, GLint t, GLint r, GLint q));
// GLGUNAKANFUNGSI(void,PFNGLMULTITEXCOORD4IVARBPROC,glMultiTexCoord4ivARB,(GLenum target, const GLint *v));
// GLGUNAKANFUNGSI(void,PFNGLMULTITEXCOORD4SARBPROC,glMultiTexCoord4sARB,(GLenum target, GLshort s, GLshort t, GLshort r, GLshort q));
// GLGUNAKANFUNGSI(void,PFNGLMULTITEXCOORD4SVARBPROC,glMultiTexCoord4svARB,(GLenum target, const GLshort *v));
GLGUNAKANFUNGSI(void,PFNGLGENQUERIESARBPROC,glGenQueriesARB,(GLsizei n, GLuint *ids));
GLGUNAKANFUNGSI(void,PFNGLDELETEQUERIESARBPROC,glDeleteQueriesARB,(GLsizei n, const GLuint *ids));
GLGUNAKANFUNGSI(GLboolean,PFNGLISQUERYARBPROC,glIsQueryARB,(GLuint id));
GLGUNAKANFUNGSI(void,PFNGLBEGINQUERYARBPROC,glBeginQueryARB,(GLenum target, GLuint id));
GLGUNAKANFUNGSI(void,PFNGLENDQUERYARBPROC,glEndQueryARB,(GLenum target));
GLGUNAKANFUNGSI(void,PFNGLGETQUERYIVARBPROC,glGetQueryivARB,(GLenum target, GLenum pname, GLint *params));
GLGUNAKANFUNGSI(void,PFNGLGETQUERYOBJECTIVARBPROC,glGetQueryObjectivARB,(GLuint id, GLenum pname, GLint *params));
GLGUNAKANFUNGSI(void,PFNGLGETQUERYOBJECTUIVARBPROC,glGetQueryObjectuivARB,(GLuint id, GLenum pname, GLuint *params));
GLGUNAKANFUNGSI(void,PFNGLMAXSHADERCOMPILERTHREADSARBPROC,glMaxShaderCompilerThreadsARB,(GLuint count));
GLGUNAKANFUNGSI(void,PFNGLPOINTPARAMETERFARBPROC,glPointParameterfARB,(GLenum pname, GLfloat param));
GLGUNAKANFUNGSI(void,PFNGLPOINTPARAMETERFVARBPROC,glPointParameterfvARB,(GLenum pname, const GLfloat *params));
GLGUNAKANFUNGSI(GLenum,PFNGLGETGRAPHICSRESETSTATUSARBPROC,glGetGraphicsResetStatusARB,(void));
GLGUNAKANFUNGSI(void,PFNGLGETNTEXIMAGEARBPROC,glGetnTexImageARB,(GLenum target, GLint level, GLenum format, GLenum type, GLsizei bufSize, void *img));
GLGUNAKANFUNGSI(void,PFNGLREADNPIXELSARBPROC,glReadnPixelsARB,(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLsizei bufSize, void *data));
GLGUNAKANFUNGSI(void,PFNGLGETNCOMPRESSEDTEXIMAGEARBPROC,glGetnCompressedTexImageARB,(GLenum target, GLint lod, GLsizei bufSize, void *img));
GLGUNAKANFUNGSI(void,PFNGLGETNUNIFORMFVARBPROC,glGetnUniformfvARB,(GLuint program, GLint location, GLsizei bufSize, GLfloat *params));
GLGUNAKANFUNGSI(void,PFNGLGETNUNIFORMIVARBPROC,glGetnUniformivARB,(GLuint program, GLint location, GLsizei bufSize, GLint *params));
GLGUNAKANFUNGSI(void,PFNGLGETNUNIFORMUIVARBPROC,glGetnUniformuivARB,(GLuint program, GLint location, GLsizei bufSize, GLuint *params));
GLGUNAKANFUNGSI(void,PFNGLGETNUNIFORMDVARBPROC,glGetnUniformdvARB,(GLuint program, GLint location, GLsizei bufSize, GLdouble *params));
GLGUNAKANFUNGSI(void,PFNGLGETNMAPDVARBPROC,glGetnMapdvARB,(GLenum target, GLenum query, GLsizei bufSize, GLdouble *v));
GLGUNAKANFUNGSI(void,PFNGLGETNMAPFVARBPROC,glGetnMapfvARB,(GLenum target, GLenum query, GLsizei bufSize, GLfloat *v));
GLGUNAKANFUNGSI(void,PFNGLGETNMAPIVARBPROC,glGetnMapivARB,(GLenum target, GLenum query, GLsizei bufSize, GLint *v));
GLGUNAKANFUNGSI(void,PFNGLGETNPIXELMAPFVARBPROC,glGetnPixelMapfvARB,(GLenum map, GLsizei bufSize, GLfloat *values));
GLGUNAKANFUNGSI(void,PFNGLGETNPIXELMAPUIVARBPROC,glGetnPixelMapuivARB,(GLenum map, GLsizei bufSize, GLuint *values));
GLGUNAKANFUNGSI(void,PFNGLGETNPIXELMAPUSVARBPROC,glGetnPixelMapusvARB,(GLenum map, GLsizei bufSize, GLushort *values));
GLGUNAKANFUNGSI(void,PFNGLGETNPOLYGONSTIPPLEARBPROC,glGetnPolygonStippleARB,(GLsizei bufSize, GLubyte *pattern));
GLGUNAKANFUNGSI(void,PFNGLGETNCOLORTABLEARBPROC,glGetnColorTableARB,(GLenum target, GLenum format, GLenum type, GLsizei bufSize, void *table));
GLGUNAKANFUNGSI(void,PFNGLGETNCONVOLUTIONFILTERARBPROC,glGetnConvolutionFilterARB,(GLenum target, GLenum format, GLenum type, GLsizei bufSize, void *image));
GLGUNAKANFUNGSI(void,PFNGLGETNSEPARABLEFILTERARBPROC,glGetnSeparableFilterARB,(GLenum target, GLenum format, GLenum type, GLsizei rowBufSize, void *row, GLsizei columnBufSize, void *column, void *span));
GLGUNAKANFUNGSI(void,PFNGLGETNHISTOGRAMARBPROC,glGetnHistogramARB,(GLenum target, GLboolean reset, GLenum format, GLenum type, GLsizei bufSize, void *values));
GLGUNAKANFUNGSI(void,PFNGLGETNMINMAXARBPROC,glGetnMinmaxARB,(GLenum target, GLboolean reset, GLenum format, GLenum type, GLsizei bufSize, void *values));
GLGUNAKANFUNGSI(void,PFNGLFRAMEBUFFERSAMPLELOCATIONSFVARBPROC,glFramebufferSampleLocationsfvARB,(GLenum target, GLuint start, GLsizei count, const GLfloat *v));
GLGUNAKANFUNGSI(void,PFNGLNAMEDFRAMEBUFFERSAMPLELOCATIONSFVARBPROC,glNamedFramebufferSampleLocationsfvARB,(GLuint framebuffer, GLuint start, GLsizei count, const GLfloat *v));
GLGUNAKANFUNGSI(void,PFNGLEVALUATEDEPTHVALUESARBPROC,glEvaluateDepthValuesARB,(void));
GLGUNAKANFUNGSI(void,PFNGLMINSAMPLESHADINGARBPROC,glMinSampleShadingARB,(GLfloat value));
GLGUNAKANFUNGSI(void,PFNGLDELETEOBJECTARBPROC,glDeleteObjectARB,(GLhandleARB obj));
GLGUNAKANFUNGSI(GLhandleARB,PFNGLGETHANDLEARBPROC,glGetHandleARB,(GLenum pname));
GLGUNAKANFUNGSI(void,PFNGLDETACHOBJECTARBPROC,glDetachObjectARB,(GLhandleARB containerObj, GLhandleARB attachedObj));
GLGUNAKANFUNGSI(GLhandleARB,PFNGLCREATESHADEROBJECTARBPROC,glCreateShaderObjectARB,(GLenum shaderType));
GLGUNAKANFUNGSI(void,PFNGLSHADERSOURCEARBPROC,glShaderSourceARB,(GLhandleARB shaderObj, GLsizei count, const GLcharARB **string, const GLint *length));
GLGUNAKANFUNGSI(void,PFNGLCOMPILESHADERARBPROC,glCompileShaderARB,(GLhandleARB shaderObj));
GLGUNAKANFUNGSI(GLhandleARB,PFNGLCREATEPROGRAMOBJECTARBPROC,glCreateProgramObjectARB,(void));
GLGUNAKANFUNGSI(void,PFNGLATTACHOBJECTARBPROC,glAttachObjectARB,(GLhandleARB containerObj, GLhandleARB obj));
GLGUNAKANFUNGSI(void,PFNGLLINKPROGRAMARBPROC,glLinkProgramARB,(GLhandleARB programObj));
GLGUNAKANFUNGSI(void,PFNGLUSEPROGRAMOBJECTARBPROC,glUseProgramObjectARB,(GLhandleARB programObj));
GLGUNAKANFUNGSI(void,PFNGLVALIDATEPROGRAMARBPROC,glValidateProgramARB,(GLhandleARB programObj));
GLGUNAKANFUNGSI(void,PFNGLUNIFORM1FARBPROC,glUniform1fARB,(GLint location, GLfloat v0));
GLGUNAKANFUNGSI(void,PFNGLUNIFORM2FARBPROC,glUniform2fARB,(GLint location, GLfloat v0, GLfloat v1));
GLGUNAKANFUNGSI(void,PFNGLUNIFORM3FARBPROC,glUniform3fARB,(GLint location, GLfloat v0, GLfloat v1, GLfloat v2));
GLGUNAKANFUNGSI(void,PFNGLUNIFORM4FARBPROC,glUniform4fARB,(GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3));
GLGUNAKANFUNGSI(void,PFNGLUNIFORM1IARBPROC,glUniform1iARB,(GLint location, GLint v0));
GLGUNAKANFUNGSI(void,PFNGLUNIFORM2IARBPROC,glUniform2iARB,(GLint location, GLint v0, GLint v1));
GLGUNAKANFUNGSI(void,PFNGLUNIFORM3IARBPROC,glUniform3iARB,(GLint location, GLint v0, GLint v1, GLint v2));
GLGUNAKANFUNGSI(void,PFNGLUNIFORM4IARBPROC,glUniform4iARB,(GLint location, GLint v0, GLint v1, GLint v2, GLint v3));
GLGUNAKANFUNGSI(void,PFNGLUNIFORM1FVARBPROC,glUniform1fvARB,(GLint location, GLsizei count, const GLfloat *value));
GLGUNAKANFUNGSI(void,PFNGLUNIFORM2FVARBPROC,glUniform2fvARB,(GLint location, GLsizei count, const GLfloat *value));
GLGUNAKANFUNGSI(void,PFNGLUNIFORM3FVARBPROC,glUniform3fvARB,(GLint location, GLsizei count, const GLfloat *value));
GLGUNAKANFUNGSI(void,PFNGLUNIFORM4FVARBPROC,glUniform4fvARB,(GLint location, GLsizei count, const GLfloat *value));
GLGUNAKANFUNGSI(void,PFNGLUNIFORM1IVARBPROC,glUniform1ivARB,(GLint location, GLsizei count, const GLint *value));
GLGUNAKANFUNGSI(void,PFNGLUNIFORM2IVARBPROC,glUniform2ivARB,(GLint location, GLsizei count, const GLint *value));
GLGUNAKANFUNGSI(void,PFNGLUNIFORM3IVARBPROC,glUniform3ivARB,(GLint location, GLsizei count, const GLint *value));
GLGUNAKANFUNGSI(void,PFNGLUNIFORM4IVARBPROC,glUniform4ivARB,(GLint location, GLsizei count, const GLint *value));
GLGUNAKANFUNGSI(void,PFNGLUNIFORMMATRIX2FVARBPROC,glUniformMatrix2fvARB,(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value));
GLGUNAKANFUNGSI(void,PFNGLUNIFORMMATRIX3FVARBPROC,glUniformMatrix3fvARB,(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value));
GLGUNAKANFUNGSI(void,PFNGLUNIFORMMATRIX4FVARBPROC,glUniformMatrix4fvARB,(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value));
GLGUNAKANFUNGSI(void,PFNGLGETOBJECTPARAMETERFVARBPROC,glGetObjectParameterfvARB,(GLhandleARB obj, GLenum pname, GLfloat *params));
GLGUNAKANFUNGSI(void,PFNGLGETOBJECTPARAMETERIVARBPROC,glGetObjectParameterivARB,(GLhandleARB obj, GLenum pname, GLint *params));
GLGUNAKANFUNGSI(void,PFNGLGETINFOLOGARBPROC,glGetInfoLogARB,(GLhandleARB obj, GLsizei maxLength, GLsizei *length, GLcharARB *infoLog));
GLGUNAKANFUNGSI(void,PFNGLGETATTACHEDOBJECTSARBPROC,glGetAttachedObjectsARB,(GLhandleARB containerObj, GLsizei maxCount, GLsizei *count, GLhandleARB *obj));
GLGUNAKANFUNGSI(GLint,PFNGLGETUNIFORMLOCATIONARBPROC,glGetUniformLocationARB,(GLhandleARB programObj, const GLcharARB *name));
GLGUNAKANFUNGSI(void,PFNGLGETACTIVEUNIFORMARBPROC,glGetActiveUniformARB,(GLhandleARB programObj, GLuint index, GLsizei maxLength, GLsizei *length, GLint *size, GLenum *type, GLcharARB *name));
GLGUNAKANFUNGSI(void,PFNGLGETUNIFORMFVARBPROC,glGetUniformfvARB,(GLhandleARB programObj, GLint location, GLfloat *params));
GLGUNAKANFUNGSI(void,PFNGLGETUNIFORMIVARBPROC,glGetUniformivARB,(GLhandleARB programObj, GLint location, GLint *params));
GLGUNAKANFUNGSI(void,PFNGLGETSHADERSOURCEARBPROC,glGetShaderSourceARB,(GLhandleARB obj, GLsizei maxLength, GLsizei *length, GLcharARB *source));
GLGUNAKANFUNGSI(void,PFNGLNAMEDSTRINGARBPROC,glNamedStringARB,(GLenum type, GLint namelen, const GLchar *name, GLint stringlen, const GLchar *string));
GLGUNAKANFUNGSI(void,PFNGLDELETENAMEDSTRINGARBPROC,glDeleteNamedStringARB,(GLint namelen, const GLchar *name));
GLGUNAKANFUNGSI(void,PFNGLCOMPILESHADERINCLUDEARBPROC,glCompileShaderIncludeARB,(GLuint shader, GLsizei count, const GLchar *const*path, const GLint *length));
GLGUNAKANFUNGSI(GLboolean,PFNGLISNAMEDSTRINGARBPROC,glIsNamedStringARB,(GLint namelen, const GLchar *name));
GLGUNAKANFUNGSI(void,PFNGLGETNAMEDSTRINGARBPROC,glGetNamedStringARB,(GLint namelen, const GLchar *name, GLsizei bufSize, GLint *stringlen, GLchar *string));
GLGUNAKANFUNGSI(void,PFNGLGETNAMEDSTRINGIVARBPROC,glGetNamedStringivARB,(GLint namelen, const GLchar *name, GLenum pname, GLint *params));
GLGUNAKANFUNGSI(void,PFNGLBUFFERPAGECOMMITMENTARBPROC,glBufferPageCommitmentARB,(GLenum target, GLintptr offset, GLsizeiptr size, GLboolean commit));
GLGUNAKANFUNGSI(void,PFNGLNAMEDBUFFERPAGECOMMITMENTARBPROC,glNamedBufferPageCommitmentARB,(GLuint buffer, GLintptr offset, GLsizeiptr size, GLboolean commit));
GLGUNAKANFUNGSI(void,PFNGLTEXPAGECOMMITMENTARBPROC,glTexPageCommitmentARB,(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLboolean commit));
GLGUNAKANFUNGSI(void,PFNGLTEXBUFFERARBPROC,glTexBufferARB,(GLenum target, GLenum internalformat, GLuint buffer));
GLGUNAKANFUNGSI(void,PFNGLCOMPRESSEDTEXIMAGE3DARBPROC,glCompressedTexImage3DARB,(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLsizei imageSize, const void *data));
GLGUNAKANFUNGSI(void,PFNGLCOMPRESSEDTEXIMAGE2DARBPROC,glCompressedTexImage2DARB,(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const void *data));
GLGUNAKANFUNGSI(void,PFNGLCOMPRESSEDTEXIMAGE1DARBPROC,glCompressedTexImage1DARB,(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLint border, GLsizei imageSize, const void *data));
GLGUNAKANFUNGSI(void,PFNGLCOMPRESSEDTEXSUBIMAGE3DARBPROC,glCompressedTexSubImage3DARB,(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, const void *data));
GLGUNAKANFUNGSI(void,PFNGLCOMPRESSEDTEXSUBIMAGE2DARBPROC,glCompressedTexSubImage2DARB,(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const void *data));
GLGUNAKANFUNGSI(void,PFNGLCOMPRESSEDTEXSUBIMAGE1DARBPROC,glCompressedTexSubImage1DARB,(GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLsizei imageSize, const void *data));
GLGUNAKANFUNGSI(void,PFNGLGETCOMPRESSEDTEXIMAGEARBPROC,glGetCompressedTexImageARB,(GLenum target, GLint level, void *img));
GLGUNAKANFUNGSI(void,PFNGLLOADTRANSPOSEMATRIXFARBPROC,glLoadTransposeMatrixfARB,(const GLfloat *m));
GLGUNAKANFUNGSI(void,PFNGLLOADTRANSPOSEMATRIXDARBPROC,glLoadTransposeMatrixdARB,(const GLdouble *m));
GLGUNAKANFUNGSI(void,PFNGLMULTTRANSPOSEMATRIXFARBPROC,glMultTransposeMatrixfARB,(const GLfloat *m));
GLGUNAKANFUNGSI(void,PFNGLMULTTRANSPOSEMATRIXDARBPROC,glMultTransposeMatrixdARB,(const GLdouble *m));
GLGUNAKANFUNGSI(void,PFNGLWEIGHTBVARBPROC,glWeightbvARB,(GLint size, const GLbyte *weights));
GLGUNAKANFUNGSI(void,PFNGLWEIGHTSVARBPROC,glWeightsvARB,(GLint size, const GLshort *weights));
GLGUNAKANFUNGSI(void,PFNGLWEIGHTIVARBPROC,glWeightivARB,(GLint size, const GLint *weights));
GLGUNAKANFUNGSI(void,PFNGLWEIGHTFVARBPROC,glWeightfvARB,(GLint size, const GLfloat *weights));
GLGUNAKANFUNGSI(void,PFNGLWEIGHTDVARBPROC,glWeightdvARB,(GLint size, const GLdouble *weights));
GLGUNAKANFUNGSI(void,PFNGLWEIGHTUBVARBPROC,glWeightubvARB,(GLint size, const GLubyte *weights));
GLGUNAKANFUNGSI(void,PFNGLWEIGHTUSVARBPROC,glWeightusvARB,(GLint size, const GLushort *weights));
GLGUNAKANFUNGSI(void,PFNGLWEIGHTUIVARBPROC,glWeightuivARB,(GLint size, const GLuint *weights));
GLGUNAKANFUNGSI(void,PFNGLWEIGHTPOINTERARBPROC,glWeightPointerARB,(GLint size, GLenum type, GLsizei stride, const void *pointer));
GLGUNAKANFUNGSI(void,PFNGLVERTEXBLENDARBPROC,glVertexBlendARB,(GLint count));
GLGUNAKANFUNGSI(void,PFNGLBINDBUFFERARBPROC,glBindBufferARB,(GLenum target, GLuint buffer));
GLGUNAKANFUNGSI(void,PFNGLDELETEBUFFERSARBPROC,glDeleteBuffersARB,(GLsizei n, const GLuint *buffers));
GLGUNAKANFUNGSI(void,PFNGLGENBUFFERSARBPROC,glGenBuffersARB,(GLsizei n, GLuint *buffers));
GLGUNAKANFUNGSI(GLboolean,PFNGLISBUFFERARBPROC,glIsBufferARB,(GLuint buffer));
GLGUNAKANFUNGSI(void,PFNGLBUFFERDATAARBPROC,glBufferDataARB,(GLenum target, GLsizeiptrARB size, const void *data, GLenum usage));
GLGUNAKANFUNGSI(void,PFNGLBUFFERSUBDATAARBPROC,glBufferSubDataARB,(GLenum target, GLintptrARB offset, GLsizeiptrARB size, const void *data));
GLGUNAKANFUNGSI(void,PFNGLGETBUFFERSUBDATAARBPROC,glGetBufferSubDataARB,(GLenum target, GLintptrARB offset, GLsizeiptrARB size, void *data));
GLGUNAKANFUNGSI(void *,PFNGLMAPBUFFERARBPROC,glMapBufferARB,(GLenum target, GLenum access));
GLGUNAKANFUNGSI(GLboolean,PFNGLUNMAPBUFFERARBPROC,glUnmapBufferARB,(GLenum target));
GLGUNAKANFUNGSI(void,PFNGLGETBUFFERPARAMETERIVARBPROC,glGetBufferParameterivARB,(GLenum target, GLenum pname, GLint *params));
GLGUNAKANFUNGSI(void,PFNGLGETBUFFERPOINTERVARBPROC,glGetBufferPointervARB,(GLenum target, GLenum pname, void **params));
GLGUNAKANFUNGSI(void,PFNGLVERTEXATTRIB1DARBPROC,glVertexAttrib1dARB,(GLuint index, GLdouble x));
GLGUNAKANFUNGSI(void,PFNGLVERTEXATTRIB1DVARBPROC,glVertexAttrib1dvARB,(GLuint index, const GLdouble *v));
GLGUNAKANFUNGSI(void,PFNGLVERTEXATTRIB1FARBPROC,glVertexAttrib1fARB,(GLuint index, GLfloat x));
GLGUNAKANFUNGSI(void,PFNGLVERTEXATTRIB1FVARBPROC,glVertexAttrib1fvARB,(GLuint index, const GLfloat *v));
GLGUNAKANFUNGSI(void,PFNGLVERTEXATTRIB1SARBPROC,glVertexAttrib1sARB,(GLuint index, GLshort x));
GLGUNAKANFUNGSI(void,PFNGLVERTEXATTRIB1SVARBPROC,glVertexAttrib1svARB,(GLuint index, const GLshort *v));
GLGUNAKANFUNGSI(void,PFNGLVERTEXATTRIB2DARBPROC,glVertexAttrib2dARB,(GLuint index, GLdouble x, GLdouble y));
GLGUNAKANFUNGSI(void,PFNGLVERTEXATTRIB2DVARBPROC,glVertexAttrib2dvARB,(GLuint index, const GLdouble *v));
GLGUNAKANFUNGSI(void,PFNGLVERTEXATTRIB2FARBPROC,glVertexAttrib2fARB,(GLuint index, GLfloat x, GLfloat y));
GLGUNAKANFUNGSI(void,PFNGLVERTEXATTRIB2FVARBPROC,glVertexAttrib2fvARB,(GLuint index, const GLfloat *v));
GLGUNAKANFUNGSI(void,PFNGLVERTEXATTRIB2SARBPROC,glVertexAttrib2sARB,(GLuint index, GLshort x, GLshort y));
GLGUNAKANFUNGSI(void,PFNGLVERTEXATTRIB2SVARBPROC,glVertexAttrib2svARB,(GLuint index, const GLshort *v));
GLGUNAKANFUNGSI(void,PFNGLVERTEXATTRIB3DARBPROC,glVertexAttrib3dARB,(GLuint index, GLdouble x, GLdouble y, GLdouble z));
GLGUNAKANFUNGSI(void,PFNGLVERTEXATTRIB3DVARBPROC,glVertexAttrib3dvARB,(GLuint index, const GLdouble *v));
GLGUNAKANFUNGSI(void,PFNGLVERTEXATTRIB3FARBPROC,glVertexAttrib3fARB,(GLuint index, GLfloat x, GLfloat y, GLfloat z));
GLGUNAKANFUNGSI(void,PFNGLVERTEXATTRIB3FVARBPROC,glVertexAttrib3fvARB,(GLuint index, const GLfloat *v));
GLGUNAKANFUNGSI(void,PFNGLVERTEXATTRIB3SARBPROC,glVertexAttrib3sARB,(GLuint index, GLshort x, GLshort y, GLshort z));
GLGUNAKANFUNGSI(void,PFNGLVERTEXATTRIB3SVARBPROC,glVertexAttrib3svARB,(GLuint index, const GLshort *v));
GLGUNAKANFUNGSI(void,PFNGLVERTEXATTRIB4NBVARBPROC,glVertexAttrib4NbvARB,(GLuint index, const GLbyte *v));
GLGUNAKANFUNGSI(void,PFNGLVERTEXATTRIB4NIVARBPROC,glVertexAttrib4NivARB,(GLuint index, const GLint *v));
GLGUNAKANFUNGSI(void,PFNGLVERTEXATTRIB4NSVARBPROC,glVertexAttrib4NsvARB,(GLuint index, const GLshort *v));
GLGUNAKANFUNGSI(void,PFNGLVERTEXATTRIB4NUBARBPROC,glVertexAttrib4NubARB,(GLuint index, GLubyte x, GLubyte y, GLubyte z, GLubyte w));
GLGUNAKANFUNGSI(void,PFNGLVERTEXATTRIB4NUBVARBPROC,glVertexAttrib4NubvARB,(GLuint index, const GLubyte *v));
GLGUNAKANFUNGSI(void,PFNGLVERTEXATTRIB4NUIVARBPROC,glVertexAttrib4NuivARB,(GLuint index, const GLuint *v));
GLGUNAKANFUNGSI(void,PFNGLVERTEXATTRIB4NUSVARBPROC,glVertexAttrib4NusvARB,(GLuint index, const GLushort *v));
GLGUNAKANFUNGSI(void,PFNGLVERTEXATTRIB4BVARBPROC,glVertexAttrib4bvARB,(GLuint index, const GLbyte *v));
GLGUNAKANFUNGSI(void,PFNGLVERTEXATTRIB4DARBPROC,glVertexAttrib4dARB,(GLuint index, GLdouble x, GLdouble y, GLdouble z, GLdouble w));
GLGUNAKANFUNGSI(void,PFNGLVERTEXATTRIB4DVARBPROC,glVertexAttrib4dvARB,(GLuint index, const GLdouble *v));
GLGUNAKANFUNGSI(void,PFNGLVERTEXATTRIB4FARBPROC,glVertexAttrib4fARB,(GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w));
GLGUNAKANFUNGSI(void,PFNGLVERTEXATTRIB4FVARBPROC,glVertexAttrib4fvARB,(GLuint index, const GLfloat *v));
GLGUNAKANFUNGSI(void,PFNGLVERTEXATTRIB4IVARBPROC,glVertexAttrib4ivARB,(GLuint index, const GLint *v));
GLGUNAKANFUNGSI(void,PFNGLVERTEXATTRIB4SARBPROC,glVertexAttrib4sARB,(GLuint index, GLshort x, GLshort y, GLshort z, GLshort w));
GLGUNAKANFUNGSI(void,PFNGLVERTEXATTRIB4SVARBPROC,glVertexAttrib4svARB,(GLuint index, const GLshort *v));
GLGUNAKANFUNGSI(void,PFNGLVERTEXATTRIB4UBVARBPROC,glVertexAttrib4ubvARB,(GLuint index, const GLubyte *v));
GLGUNAKANFUNGSI(void,PFNGLVERTEXATTRIB4UIVARBPROC,glVertexAttrib4uivARB,(GLuint index, const GLuint *v));
GLGUNAKANFUNGSI(void,PFNGLVERTEXATTRIB4USVARBPROC,glVertexAttrib4usvARB,(GLuint index, const GLushort *v));
GLGUNAKANFUNGSI(void,PFNGLVERTEXATTRIBPOINTERARBPROC,glVertexAttribPointerARB,(GLuint index, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const void *pointer));
GLGUNAKANFUNGSI(void,PFNGLENABLEVERTEXATTRIBARRAYARBPROC,glEnableVertexAttribArrayARB,(GLuint index));
GLGUNAKANFUNGSI(void,PFNGLDISABLEVERTEXATTRIBARRAYARBPROC,glDisableVertexAttribArrayARB,(GLuint index));
GLGUNAKANFUNGSI(void,PFNGLGETVERTEXATTRIBDVARBPROC,glGetVertexAttribdvARB,(GLuint index, GLenum pname, GLdouble *params));
GLGUNAKANFUNGSI(void,PFNGLGETVERTEXATTRIBFVARBPROC,glGetVertexAttribfvARB,(GLuint index, GLenum pname, GLfloat *params));
GLGUNAKANFUNGSI(void,PFNGLGETVERTEXATTRIBIVARBPROC,glGetVertexAttribivARB,(GLuint index, GLenum pname, GLint *params));
GLGUNAKANFUNGSI(void,PFNGLGETVERTEXATTRIBPOINTERVARBPROC,glGetVertexAttribPointervARB,(GLuint index, GLenum pname, void **pointer));
GLGUNAKANFUNGSI(void,PFNGLBINDATTRIBLOCATIONARBPROC,glBindAttribLocationARB,(GLhandleARB programObj, GLuint index, const GLcharARB *name));
GLGUNAKANFUNGSI(void,PFNGLGETACTIVEATTRIBARBPROC,glGetActiveAttribARB,(GLhandleARB programObj, GLuint index, GLsizei maxLength, GLsizei *length, GLint *size, GLenum *type, GLcharARB *name));
GLGUNAKANFUNGSI(GLint,PFNGLGETATTRIBLOCATIONARBPROC,glGetAttribLocationARB,(GLhandleARB programObj, const GLcharARB *name));
GLGUNAKANFUNGSI(void,PFNGLWINDOWPOS2DARBPROC,glWindowPos2dARB,(GLdouble x, GLdouble y));
GLGUNAKANFUNGSI(void,PFNGLWINDOWPOS2DVARBPROC,glWindowPos2dvARB,(const GLdouble *v));
GLGUNAKANFUNGSI(void,PFNGLWINDOWPOS2FARBPROC,glWindowPos2fARB,(GLfloat x, GLfloat y));
GLGUNAKANFUNGSI(void,PFNGLWINDOWPOS2FVARBPROC,glWindowPos2fvARB,(const GLfloat *v));
GLGUNAKANFUNGSI(void,PFNGLWINDOWPOS2IARBPROC,glWindowPos2iARB,(GLint x, GLint y));
GLGUNAKANFUNGSI(void,PFNGLWINDOWPOS2IVARBPROC,glWindowPos2ivARB,(const GLint *v));
GLGUNAKANFUNGSI(void,PFNGLWINDOWPOS2SARBPROC,glWindowPos2sARB,(GLshort x, GLshort y));
GLGUNAKANFUNGSI(void,PFNGLWINDOWPOS2SVARBPROC,glWindowPos2svARB,(const GLshort *v));
GLGUNAKANFUNGSI(void,PFNGLWINDOWPOS3DARBPROC,glWindowPos3dARB,(GLdouble x, GLdouble y, GLdouble z));
GLGUNAKANFUNGSI(void,PFNGLWINDOWPOS3DVARBPROC,glWindowPos3dvARB,(const GLdouble *v));
GLGUNAKANFUNGSI(void,PFNGLWINDOWPOS3FARBPROC,glWindowPos3fARB,(GLfloat x, GLfloat y, GLfloat z));
GLGUNAKANFUNGSI(void,PFNGLWINDOWPOS3FVARBPROC,glWindowPos3fvARB,(const GLfloat *v));
GLGUNAKANFUNGSI(void,PFNGLWINDOWPOS3IARBPROC,glWindowPos3iARB,(GLint x, GLint y, GLint z));
GLGUNAKANFUNGSI(void,PFNGLWINDOWPOS3IVARBPROC,glWindowPos3ivARB,(const GLint *v));
GLGUNAKANFUNGSI(void,PFNGLWINDOWPOS3SARBPROC,glWindowPos3sARB,(GLshort x, GLshort y, GLshort z));
GLGUNAKANFUNGSI(void,PFNGLWINDOWPOS3SVARBPROC,glWindowPos3svARB,(const GLshort *v));
